name: ReactJS

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - ./web/**

env:
  NODE_VERSION: '16.7.0'

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: test
      run: npm run test
    - name: Upload coverage to Codecov
      run: bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -F front-end