on:
  push:
    branches: [ main ]
    paths:
      - ./web/**
  pull_request:
    branches: [ main ]
    paths:
      - ./web/**

env:
  NODE_VERSION: '16.4.2'

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run test
